type Usuario {
    id: Int
    nome: String
    password: String
    token: String
}

input UsuarioInput {
    nome: String
    password: String
    token: String
}
input FiltroInput{
    id: Int
    nome: String
    token: String
}

type Query {
    usuarios: [Usuario]
}

type Mutation {
    criarUsuario(data: UsuarioInput): Usuario
    atualizarUsuario(id: Int!, data: UsuarioInput) : Usuario
    deletarUsuario(filtro: FiltroInput) : Boolean
}